### ISSUE TITLE
Short features get displaced on zoom

### ISSUE THREAD

**Issue by bene200** [calipho-sib/feature-viewer#1]
Hi,

first of all really great job with the feature viewer! I'd like to use it for a project, but I have an issue with very short features (compared to a long sequence) behaving a bit funny when I zoom in.

After first initialising the viewer, everything seems to be ok:
![intial_ok](https://cloud.githubusercontent.com/assets/9319339/12143029/37f2044a-b47d-11e5-85e3-be62cdfea54c.png)

However when I zoom in somewhere, the longer features stay ok
![zoomed_in_long_ok](https://cloud.githubusercontent.com/assets/9319339/12143041/49c9939a-b47d-11e5-92c9-3c6543b66251.png)

but the short features get displaced in a rather strange way (and I don't really understand why):
![zoomed_in_short_weird](https://cloud.githubusercontent.com/assets/9319339/12143055/62a674d2-b47d-11e5-8b00-66c6199eded6.png)

I am using version 0.1.27 of the viewer (downloaded via bower) and I followed the setup instructions from the documentation page. I would be amazing if you could please help me out with this. Please let me know if you need any further information.

Thank you very much,

Benedikt

**Comment by MatSchaeff** [comment]
Hello Benedikt,

Thank you for your appreciation ! We are glad to see that you like it and ready to use it. :)

Did you use the feature type "unique" for the features below "Exons" ?
If it's the case, you should use the type "rect" instead. I made some modifications a few month ago, and forget to tell that "unique" is deprecated. 
If not, could you please send a link of a JSFiddle or Plunker with your sample, it will be easier for me to test.

I also note that I will have to do something with the width of the labels on the left. 

Cheers,

Mathieu

**Comment by bene200** [comment]
Hello Mathieu,

thank you for the quick response! I was able to reproduce my issue in a [plunk](https://plnkr.co/edit/Yu0f2u2Bo6EMHtR70MbB?p=preview) and luckily also found out the reason I'm having it. It happens when several features have the same class name. I wasn't aware this was not intended. As soon as I give every feature a separate class name everything seems to work fine :).

Cheers,

Benedikt

**Comment by MatSchaeff** [comment]
Ok good !
I will add a note about the class names in the documentation for the next users. 

Thank you,

Mathieu
