### ISSUE TITLE
nextprot api is broken

### ISSUE THREAD

**Issue by sdevera1122** [calipho-sib/feature-viewer#10]
Hi,

It looks like api.nextprot.org is broken again.
I tried using this template (https://cdn.rawgit.com/calipho-sib/nextprot-viewers/master/peptides/app/index.html?nxentry=NX_P46976) but it doesn't work. Can you please let me know when this will be up and running.

Thanks,
Sandeep

**Comment by ddtxra** [comment]
Thanks @sdevera1122 for your interest in search.nextprot.org 
We are having a planned operation maintenance at SIB.
Tomorrow we will be up and running again.

**Comment by ddtxra** [comment]
please check now @sdevera1122

**Comment by sdevera1122** [comment]
it works.

thanks
sandeep
