### ISSUE TITLE
Transparency and rendering problem

### ISSUE THREAD

**Issue by darwinFailure** [calipho-sib/feature-viewer#11]
Hi,

I am using this library to show show in-house computed features. I have problems with transparencies and sequence axis when rendering the feature-viewer div. Check out the attached snapshot for an example of broken visualization. 

![screenshot from 2016-07-01 14 41 37](https://cloud.githubusercontent.com/assets/1375504/16521966/d7d13d52-3f9a-11e6-98f7-2fd2e46faa6d.png)

I have the d3 library and bootstrap.js loaded. Everything works (selections and callbacks) but the transparencies and the axis rendering. How can I fix it?

**Comment by harryjubb** [comment]
It looks like you might be missing the featureviewer stylesheet (`feature-viewer/css/style.css`). If you don't have that `link`ed to, does adding that help?

**Comment by darwinFailure** [comment]
That was it! Sorry for the noob question... I didn't think of css!

Thanks.

**Comment by MatSchaeff** [comment]
Not your fault, It wasn't said anywhere to also include the css file..

I updated the Readme and added feature-viewer.min.css in the dist folder. (bundle of bootstrap.css & feature-viewer css)
