### ISSUE TITLE
IE 11: Features respond only to double and not to single clicks

### ISSUE THREAD

**Issue by harryjubb** [calipho-sib/feature-viewer#12]
Unfortunately I have to support >= IE 11 for the project I'm working on.

In IE, a single click on a feature doesn't fire the `onFeatureSelected` event, but it does fire on a double click. Any thoughts on why this may be and how to fix it would be greatly appreciated :)

I'm using feature-viewer version 2016-05-25.

**Comment by MatSchaeff** [comment]
Hello Harry, 
Closing some old issues here, sorry for the late reply..
If I remember correctly I did try to find the problem, and finally fixed it in the newest versions. 
Tell me if it's still a problem though.
