### ISSUE TITLE
IE 11: Painting of feature tracks is truncated

### ISSUE THREAD

**Issue by harryjubb** [calipho-sib/feature-viewer#13]
Another IE issue; with features with many tracks, the tracks are painted for a consistent but seemingly arbitrary way down the page, but are then truncated. Please see example below.

This seems only to be an issue vertically and not horizontally. 

![pasted_image_06_07_2016__12_17](https://cloud.githubusercontent.com/assets/4588417/16616287/238db356-4374-11e6-89d6-c70865b2d881.png)

**Comment by harryjubb** [comment]
Thanks to the JS diagnostic skills of @fredludlow, we've discovered that this is caused by the `#clip > rect`'s `height` attribute.

This is set to `570` by default, increasing this shows the rest of the feature's tracks. Setting to `100%` seems to work fine in IE11 and Chrome.

The default `570` limit is applied on a per-feature basis, so doesn't affect features with heights less than 570px.

**Comment by MatSchaeff** [comment]
Hello Harry,

Yes, this was a known issue for all browser, but i fixed it since the v0.1.41 ;)

I found some proteins with a lot of overlapping peptides so i had to fix it.
The FV now use a more clear method to update SVG height.

**Comment by harryjubb** [comment]
Hi Mathieu,

Excellent! Thank you :) great to hear it's fixed.
