### ISSUE TITLE
[enhancement] Selectively allow click on features track

### ISSUE THREAD

**Issue by ftabaro** [calipho-sib/feature-viewer#14]
Hi,

This time, I'd like to ask whether there is the possibility to enable/disable the mouse selection on a track basis. I.e. I would like to tell the viewer which tracks can be clicked (triggering the .onFeatureSelected method) and which not. Is this feature supported in any way? How hard would be to implement it?

**Comment by MatSchaeff** [comment]
Hello,
Sorry for the late reply, 
Thank you for your suggestion, but unfortunately this is not supported for now.
If I have time, I will check how it could be implemented.
