### ISSUE TITLE
[Question] hide and show feature tracks

### ISSUE THREAD

**Issue by bene200** [calipho-sib/feature-viewer#15]
Hello,

I'm trying to programmatically hide and show specific tracks with the feature-viewer. I would like to achieve similar behaviour to the filtering functionality in neXtprot. 

I couldn't find how to do this in the documentation, however I've discovered that the feature viewer object has 'hideFilteredFeatures and showFilteredFeatures' functions.
I've been trying to do [this](https://jsfiddle.net/qwq5ws2u/1/), however, I did not have much success. 

Is there an example somewhere that shows how tracks can be hidden/displayed?

Thank you very much for your help,

Benedikt

**Comment by harryjubb** [comment]
I haven't yet implemented it yet, but as I understand from talking to @MatSchaeff and @fredludlow, the only way to do this currently is to tear down the viewer and rebuild it with/without the tracks you want shown/hidden.

The show and hide FilteredFeatures adds highlighting to the labels of tracks, but doesn't show/hide the whole track, as I understand it.

**Comment by bene200** [comment]
Right, I see. Thank you very much for the info, I'm going to try with rebuilding the viewer then.

**Comment by harryjubb** [comment]
Just an FYI, as I started doing this; you'll want to call the `clearInstance` method to tear down e.g. event handlers, before you rebuild the viewer (#8).

**Comment by neon-ninja** [comment]
I wrote a working example of this at https://github.com/UoA-eResearch/feature-viewer/blob/8c725d792d48c7ed4f4ef87583c584189f0d91a8/examples/toggle_features.html

https://cdn.rawgit.com/UoA-eResearch/feature-viewer/8c725d792d48c7ed4f4ef87583c584189f0d91a8/examples/toggle_features.html
