### ISSUE TITLE
How can we show DNA and Protein Sequence together??

### ISSUE THREAD

**Issue by cdtiwari** [calipho-sib/feature-viewer#16]
I like this api very much. Amazing work done guys.
When I see this API, i thought of using this in my project but I have slightly different approach.

As per my requirement I have to show both the sequence in sequence bar.
I am passing ntsequence and drawing featuremap but after this i get another requirement to show DNA and protein(amino acid) sequence in same track.

Can you guys please help me to do this.??

**Comment by definitelysean** [comment]
+1

In other words, is it possible to implement a feature type which is effectively a second sequence? For example, what if you wanted the primary sequence to coding DNA, and you wanted to show the corresponding amino acid for each codon as a feature?

**Comment by MatSchaeff** [comment]
Thank you for your suggestion. Yes it could be interesting to have 2 different sequences displayed. Unfortunately, this option is not possible for now, and we don't have time to implement it anytime soon. 
However one workaround could be to create 2 instances of the feature viewer and link the mouse events between them.
