### ISSUE TITLE
Coordinates with an offset

### ISSUE THREAD

**Issue by homonecloco** [calipho-sib/feature-viewer#2]
Hi,
To work in genomic data, the coordinate systems very often start in large numbers. I think it would be valuable to enable have an option called offset, and change the scale accordingly. It would be possible to receive the coordinates with the offset and then subtract them in the add method. Have you considered this? 
Best, 
Ricardo.

**Comment by MatSchaeff** [comment]
Hello Ricardo,

If i understand correctly, you would like to initialize the sequence viewer with a window in a large sequence ?
For exemple, create a feature viewer with a large sequence and an option like start:100'000 to end:110'000 ? 
Can you confirm ?
If this is the case, there will be no need to change the add method, it will scale accordingly. 
However I will need to change the global scale, and the zoom method.

That's a good idea, I will take a look in the next weeks, keep you in touch.
If you want to do it yourself, you can send a pull-request on github.

Thank you for your suggestion and for using our component ! :)

Mathieu

**Comment by homonecloco** [comment]
Yes, that is what I want to do. However, I won't want to add the full sequence, as that could be several megabases, so it can potentially kill the component. 
Actually, I don't need the sequence, so just having a window on a range could work perfectly fine, provided that I don't need to provide a sequence. 

I'll probably start integrating the component in the next couple of weeks, so once I'm more familiar with it I can patch it, but I'll let you know if I get lost in the code. 
Best, 
Ricardo.

**Comment by MatSchaeff** [comment]
For now, the feature viewer needs a sequence to be initialized, but it could also be a number (sequence length).
That's something i wanted to implement for some time. 
I'm a bit busy on other projects right now, but I will try to take a look when i have time !

Of course, don't hesitate to ask question if you need some help with the code !

Cheers,
Mathieu.

**Comment by jmvillaveces** [comment]
Hi,

I work with genomic data as well and the functionality @homonecloco described before is just what I need for a project.

Is someone already working on it?

Cheers,
José.

**Comment by homonecloco** [comment]
Hi José, 
I haven't got the chance to work on this, I expect to be needing it in a month or so, so it is when I *may* start poking this code. If you have the time to hack it I would be very grateful. 
Best, 
Ricardo

**Comment by MatSchaeff** [comment]
Hi all,

I've begun to implement the responsive layout of the feature-viewer last week, I'll probably follow with this functionnality for large sequence next week.
Keep in touch,

Cheers,
Mathieu

**Comment by MatSchaeff** [comment]
Hello again,

I've finished the implementation, it is available on the new release : 
https://github.com/calipho-sib/feature-viewer/releases/tag/v0.1.36

Thank you for your suggestion & for using the feature-viewer ! :)

Cheers,
Mathieu
