### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by ftabaro** [calipho-sib/feature-viewer#23]
Hello, 

this library do not compile as external dependency while using webpack. I've found out that the whole thing are a couple of bootstrap font files missing: `glyphicons-halflings-regular.svg` and `glyphicons-halflings-regular.ttf`. I included them in the proper folder and magically the whole thing compile. If you wish I can submit a PR.

Cheers

**Comment by MatSchaeff** [comment]
Hello,
Sorry for the late reply, 
Glyphicons are not longer required, if the bootstrap file appears to be an issue with your compilation I would recommend to load only the feature-viewer css file and import bootstrap css separately.
Cheers
