### ISSUE TITLE
Rezising from small pages issue

### ISSUE THREAD

**Issue by Lisanna** [calipho-sib/feature-viewer#24]
![schermata](https://user-images.githubusercontent.com/8490781/29120510-d1b3506e-7d0a-11e7-9342-8e97ec264515.png)

As from the image, captured directly from live demo https://cdn.rawgit.com/calipho-sib/feature-viewer/v1.0.0/examples/index.html.
The problem originates when the viewer is initially loaded in a small page (try a page with approximately the width of the viewer) and the page is then enlarged (try size-wise window button). 

I would like to include the feature viewer in my web app, but I need it to be initially visualized in a small section eventually enlarged and it always shows this issue.
Thanks.

**Comment by MatSchaeff** [comment]
Fixed in the newest versions (http://calipho-sib.github.io/feature-viewer/examples/)
