### ISSUE TITLE
Viewer does not handle parent container resize

### ISSUE THREAD

**Issue by harryjubb** [calipho-sib/feature-viewer#3]
On resizing the parent container div, e.g. on a window resize where the div width is set dynamically, the viewer stays the same size.

Is there a way to have the viewer handle the resize when it's parent container changes size?

Using 0.1.35 from npm.

**Comment by MatSchaeff** [comment]
Hello Harry,

Yes, I'm working on it ;)
It will be available on the next release soon.

Cheers,
Mathieu

**Comment by harryjubb** [comment]
Hi Mathieu,

That's great news! Thanks for releasing this awesome project :)

Best,

Harry

**Comment by MatSchaeff** [comment]
Hello Harry,

The responsive layout is now working ! 
https://github.com/calipho-sib/feature-viewer/releases/tag/v0.1.36

Thank you for using it ! :)

Cheers,
Mathieu

**Comment by harryjubb** [comment]
Amazing, thank you! @fredludlow.

**Comment by harryjubb** [comment]
Responsiveness looks great! :)
