### ISSUE TITLE
[Bug] Extra space beneath a track with a pile of rect's

### ISSUE THREAD

**Issue by har-wradim** [calipho-sib/feature-viewer#32]
When the number of rect elements in a track piled on top of each other exceeds ~35, the space beneath starts increasing disproportionally, such that at ~100 half of the track is white space:

https://jsfiddle.net/har_wradim/yh89nodj/

**Comment by har-wradim** [comment]
OK, it seems that the bug is slightly different: the white space appears because of incorrect clipping applied to the track's rectangle. Thus, bottommost items become hidden and white space is left behind.

**Comment by MatSchaeff** [comment]
Hello har-wradim,
Sorry for the late reply, do you still have this problem ? 
From the jsfiddle you provided I couldn't see where the problem was.
