### ISSUE TITLE
rawgit is shutting down

### ISSUE THREAD

**Issue by bradfordcondon** [calipho-sib/feature-viewer#35]
Hello thank you for providing an awesome piece of software.

https://rawgit.com/

As you can see Rawgit is shutting down October 2019.  I'd love to keep using your package, how about something like https://www.jsdelivr.com/rawgit ?

**Comment by MatSchaeff** [comment]
Hello bradfordcondon, 

We are glad that you appreciate our tool!
You're right, I will modify the links with jsdelivr, thank you for your suggestion!

By the way, it seems jsdelivr doesn't allow to host a webpage like rawgit did for our [demo page](https://cdn.rawgit.com/calipho-sib/feature-viewer/v1.0.4/examples/index.html).
Do you know any alternative ? I saw that Github now provides "Github Pages" but it seems that it requires to create another repository with ".io"

Best regards,
Mat

**Comment by bradfordcondon** [comment]
Is your demo page a static site?  if so github pages would work just fine.  You can hook it up to a ]custom domain no problem](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site).

**Comment by MatSchaeff** [comment]
I updated the links with jsdeliver and the demo page with Github Pages.
Thank you!
