### ISSUE TITLE
Override hover message

### ISSUE THREAD

**Issue by gerdos** [calipho-sib/feature-viewer#36]
I want to completely overwrite the hover message on features. My problem is that if i give the "description" option, it only adds the text to the current hover message, is there a way to completely overwrite the default text?

**Comment by MatSchaeff** [comment]
Hello gerdos,
By default, the tooltip shows the start/end positions of the feature. If a description option is provided, it is indeed added below. To remove this initial line or completely overwrite the tooltip, it would require to change the internal code of the feature-viewer. Unfortunately you would need to fork this project and do it yourself.
If you don't mind the positional information, you can still add html in the description option to custom a bit the tooltip content.
