### ISSUE TITLE
onFeatureDeselected not present in bundle

### ISSUE THREAD

**Issue by kenietz** [calipho-sib/feature-viewer#37]
Hi,
maybe it is not a real issue but is a problem for me. 

I just figured that onFeatureDeselected is not available in the feature-viewer.bundle.js but is available in the source code of feature-viewer.js here on github. 

Is it possible to get a bundle with this function available?
Or is there another way to catch the deselecting? Maybe i missed something.

Thank you for your good work and any help you might provide!

**Comment by MatSchaeff** [comment]
Hello,
Thank you for this bug report. This function is now in the bundle!
Cheers
