### ISSUE TITLE
Download as SVG

### ISSUE THREAD

**Issue by sunworshipper** [calipho-sib/feature-viewer#39]
It would be nice to have an option to download the view as svg so it can be manipulated easily in Illustrator.  At the moment a workaround is to save html as pdf and import pdf.

**Comment by MatSchaeff** [comment]
I agree, this is a feature we wanted to add for a long time. I will try to see how to implement it soon. Meanwhile, the typescript version of the feature-viewer is already including this option ;)
https://github.com/BioComputingUP/feature-viewer-typescript

**Comment by kwsamarasinghe** [comment]
SVG download is available from feature viewer version 1.3.0-beta.10. Please check it out.
