### ISSUE TITLE
How to zoom out programmatically

### ISSUE THREAD

**Issue by vbazurtob** [calipho-sib/feature-viewer#4]
Hi,

I would like to zoom out programmatically. I want to implement a button and then fire the zoom out functionality with that button. How can I achieve that?

**Comment by MatSchaeff** [comment]
Dear Vbazurtob,

This functionality is not available yet, but i'm working on it.
Keep in touch,

Best,
Mathieu

**Comment by MatSchaeff** [comment]
Hello,

I released a new version of the feature-viewer.
https://github.com/calipho-sib/feature-viewer/releases/tag/v0.1.40

You can now zoom programmatically with two new methods :
- **```zoom(start,end)```** : The feature viewer will zoom on the coordinates passed in parameters.
- **```resetZoom()```** : Will reset the zoom.

Check out the documentation for examples : 
https://cdn.rawgit.com/calipho-sib/feature-viewer/v0.1.40/examples/index.html

Cheers,
Mathieu
