### ISSUE TITLE
Turn off "+Add Variants" button

### ISSUE THREAD

**Issue by n-szulc** [calipho-sib/feature-viewer#58]
Hello,

how do I completely turn off displaying the +Add Variants button?

Best regards

**Comment by PaulGuerry** [comment]
Hello,

I would also like to know how to turn off the "+ Add Variants" button.

Cheers

**Comment by kwsamarasinghe** [comment]
Hi

Please use the latest beta version 1.3.0-beta.10, which by default removes this button. 
Hope it helps.

Kasun
