### ISSUE TITLE
Error on var FeatureViewer = require('feature-viewer')

### ISSUE THREAD

**Issue by tkakar** [calipho-sib/feature-viewer#65]
When I try to import the library using Error on `var FeatureViewer = require('feature-viewer')`
I get the following error. Can anyone please help me?
... node_modules/bootstrap/js/src/tooltip.js:8
import * as Popper from '@popperjs/core'
^^^^^^
SyntaxError: Cannot use import statement outside a module
Tried installing different versions of popper and bootstrap but still got the error.

**Comment by kwsamarasinghe** [comment]
You have to do it as `import { createFeature } from "feature-viewer"` for ES2015 or `const { createFeature } = require("feature-viewer")` for node apps.
