### ISSUE TITLE
Regarding nextprot api

### ISSUE THREAD

**Issue by sdevera1122** [calipho-sib/feature-viewer#7]
Hi,

Im trying to use this template (https://cdn.rawgit.com/calipho-sib/nextprot-viewers/master/peptides/app/index.html?nxentry=NX_P46976) and looks like api.nextprot.org is broken. Can you please check and fix it.

Thanks,
Sandeep

**Comment by MatSchaeff** [comment]
Hello Sandeep,

There was an extraordinary server maintenance from 5pm GMT yesterday till this morning, but it's up again now !
Thank you for using our components.

Best,
Mathieu

**Comment by sdevera1122** [comment]
It works now. Thanks for fixing and developing good apps.

On Thu, May 19, 2016 at 3:00 AM, Mathieu Schaeffer <notifications@github.com
