### ISSUE TITLE
Clean disposal of feature-viewer instance

### ISSUE THREAD

**Issue by fredludlow** [calipho-sib/feature-viewer#8]
This is somewhat related to the use-case mentioned in #5. At them moment I'm allowing users to toggle features, implemented by deleting and recreating the container element, then recreating a feature-viewer instance. This is (perhaps unsurprisingly) slowly leaking memory - I guess due to circular references between DOM and JS created by event handlers. Would it possible (or is there already) a convenient "dispose" function on the feature-viewer that would remove these?

**Comment by MatSchaeff** [comment]
Hey Fred,
Very good remark !
I also have a system of filters (https://search.nextprot.org/entry/NX_P01308/view/sequence), and i have to recreate an instance each time a filter is applied. As you mentioned, there are indeed some memory leaks with the listeners. I will look into it !

On the another hand, we shouldn't have to recreate an instance, there should be some methods to add or delete a feature at a specific index without having to recreate entirely the feature-viewer..
This could be useful in many cases, like yours ( #5 ), and in genomics in general, where there are probably a lot of features, along sequences of millions of residues.
I noticed that when there are more than 3000 nodes in the features viewer, the zoom begins to be slow and laggy.. So i removed the transition animation, but that's not enough.. Your work-around, by adding the feature only at a specific zoom level could resolve this problem.

Keep in touch,

Mathieu

**Comment by fredludlow** [comment]
Ah, I hadn't actually thought of doing it like that...

My use-case is I have hundreds of features (rows) most of which contain very sparse data, so I have a single summary row and a (separate) widget to turn on and off the individual rows. Toggling a row currently causes a complete re-creation of the viewer, which resets the zoom - so I was hoping I could use `offset` to supply an initial zoom (and hide the re-creation from the user), but that actually stops you being able to zoom out beyond the range specified in `offset`. 

An ability to toggle features/rows without recreating the instance would be good, but that does look like a bigger change!

Fred

**Comment by MatSchaeff** [comment]
Oh ok, I see !

Well, you will be able to do that with the new version i just released, it now has methods to programmatically zoom into the feature-viewer as requested in #5 .

I also added a method **```clearInstance()```** to avoid memory leaks when re-creating an instance. 

https://github.com/calipho-sib/feature-viewer/releases/tag/v0.1.40

About the ability to toggle features, it may be a bit more complicated yes. I will look into it, maybe for the next release.

Cheers,
Mat

**Comment by fredludlow** [comment]
That's great, thanks very much!
