### ISSUE TITLE
Incompatability with Apache 2 License

### ISSUE THREAD

**Issue by akmorrow13** [calipho-sib/feature-viewer#9]
I would love to use this library! However, the license is not compatible with Apache 2 License.

**Comment by ddtxra** [comment]
Hello @akmorrow13 , thanks for your interest in our library :) 
I will check if we can upgrade it to GPL v3, would that be ok for you? Looks like they are compatible

**Comment by ddtxra** [comment]
Hello @akmorrow13 we have updated the license to GPL v2 or later. Since GPL v3 is compatible with Apache 2, you should be able to use our library.

**Comment by akmorrow13** [comment]
Great thanks for the quick response!
Best,

Alyssa Morrow
akmorrow@berkeley.edu <mailto:akmorrow@berkeley.edu>
414-254-6645

**Comment by ddtxra** [comment]
It would be awesome if afterwards you could send us a link where it is deployed (if public).
We would like to do a small paragraph in the readme with the different deployed versions

**Comment by akmorrow13** [comment]
Ok sounds good! We moved to pileup.js right after the licensing thing but they have a poor feature display. I will talk to the frontenders to possibly integrate these together. I think that would be awesome!

Best,

Alyssa Morrow
akmorrow@berkeley.edu <mailto:akmorrow@berkeley.edu>
414-254-6645
